insert into teams values (1, 'Barcelona', 'Spain');
insert into teams values (2, 'Liverpool', 'England');
insert into teams values (3, 'Al Nassr', 'Saudi Arabia');
insert into teams values (4, 'Spartak', 'Russia');
insert into teams values (5, 'Kairat', 'Kazakhstan');
insert into players values(1, 'Lionel', 'Messi', 'Argentina');
insert into players values(2, 'Mohamed', 'Salah', 'Egypt');
insert into players values(3, 'Cristiano', 'Ronaldo', 'Portugal');
insert into players values(4, 'Denis', 'Glushakov', 'Russia');
insert into players values(5, 'Danil', 'Ustimenko', 'Kazakhstan');
insert into stadiums values(1, 'Almaty Central Stadium', 'Almaty', 'Kazakhstan');
insert into stadiums values(2, 'Beijing National Stadium', 'Beijing', 'China');
insert into stadiums values(3, 'Lusail Stadium', 'Lusail', 'Qatar');
insert into stadiums values(4, 'Luzhniki Stadium', 'Moscow', 'Russia');
insert into stadiums values(5, 'Stadio Olimpico', 'Rome', 'Italy');
insert into timeslots values(1, '13:00');
insert into timeslots values(2, '13:30');
insert into timeslots values(3, '16:00');
insert into timeslots values(4, '18:00');
insert into timeslots values(5, '19:45');